name = "mumble"
main = "worker/index.js"
compatibility_date = "2026-08-06"
assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "mumble-db"
database_id = "84f84025-48a6-43c4-97ce-35f605cc99ee"

[vars]
ADMIN_NAME = "admin"
